# Generated by Django 4.1.6 on 2023-09-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('name_cript', models.CharField(max_length=15, verbose_name='Название крипты')),
                ('side', models.CharField(max_length=15, verbose_name='Сторона')),
                ('price', models.DecimalField(decimal_places=7, max_digits=12, verbose_name='Цена')),
                ('count', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Количество')),
                ('all_cost', models.DecimalField(decimal_places=7, max_digits=12, verbose_name='Всего')),
            ],
            options={
                'verbose_name_plural': 'Данные ордеров',
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
