# Generated by Django 4.1.6 on 2023-09-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0002_orders_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='all_cost',
            field=models.CharField(max_length=20, verbose_name='Всего'),
        ),
        migrations.AlterField(
            model_name='vision',
            name='count',
            field=models.CharField(max_length=20, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='vision',
            name='price',
            field=models.CharField(max_length=20, verbose_name='Цена'),
        ),
    ]
